### ISSUE TITLE
bug:类似`#00000030`这种写法的颜色无法替换

### ISSUE THREAD

**Issue by free-pan** [hzsrc/webpack-theme-color-replacer#18]
## 问题描述:

使用的是ant-design-pro-vue, 如下颜色写法,在主题切换时无法替换:

第一种写法:(此种写法的颜色,在打包之后,不能随着主题的改变而改变)
`box-shadow: 0 0 0 2px color('@{primary-color}30');` 这里这个`30`表示透明度
```css
.ant-input:focus {
  border-color: #40a9ff;
  outline: 0;
  box-shadow: 0 0 0 2px color('@{primary-color}30');
  border-right-width: 1px !important;
}
```

第二种写法:(此种写法的颜色,在打包之后,可以随着主题的改变而改变)
`box-shadow: 0 0 0 2px color('@{primary-color}');`
```css
.ant-input:focus {
  border-color: #40a9ff;
  outline: 0;
  box-shadow: 0 0 0 2px color('@{primary-color}');
  border-right-width: 1px !important;
}
```

## 期望结果

第一种写法也能在主题切换时达到,颜色值也可替换

## 其它说明

使用`tyarn run server`方式运行时, 第一种写法也是生效的, 但`build`之后就无效了
