### ISSUE TITLE
关于 HSLA  色彩模式的支持

### ISSUE THREAD

**Issue by iczer** [hzsrc/webpack-theme-color-replacer#48]
首先，非常感谢您的贡献。

我这边开发时出现一个问题，在开发环境下颜色替换都能正常运作，但一打包部署生产颜色替换就失效了。
后面发现是vue-cli3 build 时，modern浏览器下会将 rgba 颜色编译为 hsla 色彩模式，导致rgba颜色在生产环境无法替换。

所以问下作者可否增加下 hsla 色彩模式的支持?

**Comment by hzsrc** [comment]
应该可以支持的。想问下你那边编译出来的hsla是什么样的格式（比如精确到小数点多少位）？
比如3位：
```css
.hsl {
    background: hsl(27, 92.531%, 52.745%);
    background: hsla(27, 92.531%, 52.745%, 0.5);
}
```
